name: Release

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'Version to release'
            required: true

env:
    VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: Path.${{ env.VERSION }}.nupkg

  deploy-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: nupkg

    - name: Push to GitHub feed
      run: dotnet nuget push Path.${{ env.VERSION }}.nupkg --source https://nuget.pkg.github.com/ssg/index.json --api-key ${{ secrets.GPM_TOKEN }}

  deploy-nuget:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: nupkg

    - name: Push to NuGet feed
      run: dotnet nuget push Path.${{ env.VERSION }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}        
